config/routes.rb
DbcOverflow::Application.routes.draw do

  resources :users

   post '/sessions', :to => 'sessions#start', :as => 'start_session'
   get '/sessions/new', :to => 'sessions#new', :as => 'new_session'
   match 'logout', :to => "sessions#delete", :as => 'logout'

  resources :questions, except: [:destroy] do
    resources :comments

    resources :answers do
      resources :comments
    end
  end

  root :to => 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :answer_text

  belongs_to :question
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :votes,  as: :votable

  validates_presence_of :answer_text
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :user_id
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :votes, as: :votable
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :question_text, :title, :tag_namez
  attr_accessor :tag_namez

  belongs_to :user
  has_many   :answers
  has_many   :comments, as: :commentable
  has_many   :votes,    as: :votable
  has_many :taggings, dependent: :destroy
  has_many   :tags, through: :taggings

  validates_presence_of :question_text
  validates_presence_of :title

  after_save :assign_tags

  def tag_name
    @tags = self.tag_namez.split(', ')
    string = ''
    @tags.each {|tag| string << tag.tagname + ","}
    string.chop 
  end

  private

  def assign_tags
    array_of_tags = tag_namez.split(', ').uniq
    array_of_tags.each do |tag|
      newtag = Tag.find_or_create_by_tagname(tag)
      self.tags << newtag unless taggings.include?(newtag.id)
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, dependent: :destroy
  has_many :questions, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :question
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :answers
	has_many :questions
  has_many :comments
  has_many :votes
	validates_presence_of :username
	validates_presence_of :email
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

	attr_accessible :username, :email, :password, :password_confirmation
	has_secure_password

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :choice
  belongs_to :user
  belongs_to :votable, polymorphic: true
  # belongs_to :commentable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(params[:answer])
    @answer.user_id = session[:user_id]

    if @answer.save
      @question.answers << @answer
      if request.xhr?
        render json: @answer
      else
        redirect_to question_url(@question)
      end
    else
      @errors = @answer.errors
      render 'new'
    end
    
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    if @answer.update_attributes(params[:answer])
      redirect_to question_url(@question)
    else
      @errors = @answer.errors
      render 'edit'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def show
    answer = Answer.find(params[:answer_id])
    @comments = answer.comments.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    redirect_to action: 'index' if session[:user_id].nil?
    @question = Question.new
  end

  def create
   @question = Question.new(params[:question])
   puts params.inspect + "*"*800
   @question.tag_namez = params[:question][:tag_namez]
   puts @question.tag_namez
   @question.user_id = session[:user_id]
   if !session[:user_id].nil? && @question.save
      redirect_to "index"
   else
      @errors = @question.errors
      render 'new'
   end
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update_attributes(params[:question])
      redirect_to action: 'index'
    else
      @errors = @question.errors
      render 'edit'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include UserHelper

  def start
    @user = User.find_by_email(params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id

      redirect_to user_url(session[:user_id])
    else
      @user = User.new
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def delete
    session.clear
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	include UserHelper

	def create
		user = User.create(params[:user])

		if user.persisted?
			session[:user_id] = user.id
			redirect_to user_url(session[:user_id])
		else
			redirect_to new_user_url
		end
	end

	def new
		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
	end

	def show
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])
		if user.update_attributes(username: params[:user][:username]) && user.save
			redirect_to user_url
		else
			redirect_to edit_user_url(user)
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
	def current_user
		@user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/views/answers/_answer.html.erb
<ul id= "answers">
  <% @question.answers.each do |answer| %>
    <li>
      <%= answer.answer_text %>
    </li>
  <% end %>
</ul>

<div id="new-answer">
  <h2>Create a New Answer</h2>

  <%= render 'answers/form', locals: {answer: @question.answers.new}, layout: false %>
</div>

app/views/answers/_form.html.erb
<% @answer ||= locals[:answer] %><%= form_for [@question, @answer] do  |a| %>
  <% if @answer.errors.any? %>
    <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li style="color:red;">
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <br>
  <%= a.text_area :answer_text, :placeholder => "Enter your answer" %>
  <br>
  <br>
  <%= a.submit %>
  <br>
  <br>
<% end %>

app/views/answers/_show.html.erb
# params
#   @answer
#   @comments

<ul>
  <li>
      answer.answer_text
  </li>

  <li>
      <!-- passing in @comments into partial -->
      <%= render template: "comments/show", local: {comments: answer_comments} %>
  </li>
</ul>

app/views/answers/edit.html.erb
<h2>Edit Answer</h2>

<%= render 'form' %>

app/views/answers/new.html.erb
<div id="new-answer">
  <h2>Create a New Answer</h2>

  <%= render 'form', layout: false %>
</div>

app/views/comments/_show.html.erb
# params
#    @comments

<ul>
  <% comments.each do |comment| %>
   <li><%= comment.body %></li>
  <% end %>
</ul>

app/views/comments/show.html.erb
<ul>
  <% @comments.each do |comment| %>
    <li>
      <%= comment.body %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DbcOverflow</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% unless session[:user_id] %>
      <span>
        <%=  link_to  "Sign In", new_session_path %>
        <%= link_to "Sign Up", new_user_path %>
      </span>
    <%  else %>
      <%= link_to "Log Out", logout_path %>
      <%= link_to "Back to Questions", questions_path, method: :get %>
      <%= link_to "Add question", new_question_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |q| %>
  <% if @question.errors.any? %>
    <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li style="color:red;">
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <%= q.text_field :title, :placeholder => "Enter a title" %>
  <br>
  <br>
  <%= q.text_area :question_text, :placeholder => "Enter your question" %>
  <br>
  <br>
  <%= q.text_field :tag_namez %>
  <br>
  <br>
  <%= q.submit %>
<% end %>

app/views/questions/edit.html.erb
<h2>Edit Question</h2>

<%= render 'form' %>

app/views/questions/index.html.erb
<div>
  <h2>Questions</h2>

  <ul>
    <% @questions.each do |question| %>
      <li>
        <%=  link_to  question.title, question_path(question) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/questions/new.html.erb
<h2>Create a New Question</h2>

<%= render 'form' %>

app/views/questions/show.html.erb
<h2><%= @question.title %></h2>

<strong><%= @question.user.username if @question.user.present? %></strong>

<h3><%= @question.question_text %></h3>

<% @question.tags.each do |tag| %>
  <li>
    <%= tag.tagname %>
  </li>
<% end %>

<%= render partial: "/answers/answer" %>

<%= link_to "Add Answer", '#', :id => "add-answer" %>

app/views/users/_form.haml
= form_for @user do |f| 
	- if @user.errors.any?
		%h2= pluralize(@user.errors.count, "error")
		%ul
			- @user.errors.full_messages.each do |message|
				%li= message 

	.field= f.label :username
	.field= f.text_field :username
	.field= f.label :email
	.field= f.text_field :email
	.field= f.label :password
	.field= f.password_field :password
	.field= f.label :password_confirmation
	.field= f.password_field :password_confirmation
	.field= f.submit

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<h2><%= pluralize(@user.errors.count, "error") %></h2>
		<ul>
 			<% @user.errors.full_messages.each do |message| %>
				<li>
					<%= message %>
			  </li>
			<% end %>
    </ul>
  <% end %>

	<%= f.label :username %>
	<br>
	<%= f.text_field :username %>
  <br>
  <br>
	<%= f.label :email %>
	<br>
	<%= f.text_field :email %>
  <br>
  <br>
	<%= f.label :password %>
	<br>
	<%= f.password_field :password %>
  <br>
  <br>
	<%= f.label :password_confirmation %>
	<br>
	<br>
	<%= f.password_field :password_confirmation %>
	<br>
	<br>
	<%= f.submit %>
<% end %>

app/views/users/_sform.haml
= form_for @user do |f|
	- if @user.errors.any?
		%h2= pluralize(@user.errors.count, "error")
		%ul
			- @user.errors.full_messages.each do |message|
				%li= message

	.field= f.label :username
	.field= f.text_field :username
	.field= f.label :email
	.field= f.text_field :email
	.field= f.label :password
	.field= f.password_field :password
	.field= f.label :password_confirmation
	.field= f.password_field :password_confirmation
	.field= f.submit

app/views/users/edit.haml
%h2 Edit!

= render :partial => "form"

app/views/users/edit.html.erb
%h2 Edit!

= render :partial => "form"

app/views/users/new.haml
%h2 Sign up!

= render partial: "form"

app/views/users/new.html.erb
<h2>Sign up!</h2>

<%= render partial: "form" %>

app/views/users/show.haml
%p= @user.username
%p= @user.email

- if session[:user_id]
  = link_to "Log Out", logout_path
  = link_to "Back to Questions", questions_path, method: :get

app/views/users/show.html.erb
<h2><%= @user.username %></h2>
<h4><%= @user.email %></h4>